frontend/controllers/MainController.php
<?php

namespace frontend\controllers;

use frontend\models\UploadForm;
use yii\web\Controller;
use Yii;
use yii\web\Response;
use yii\web\UploadedFile;

class MainController extends Controller
{
    /**
     * @return string
     */
    public function actionIndex()
    {
        Yii::$app->minio->setBucket('public');
        $model = new UploadForm();

        return
            $this->render(
                'index',
                [
                    'model' => $model,
                    'listObjects' => Yii::$app->minio->listObjects()
                ]
            );
    }

    /**
     * @param $filename
     * @return mixed
     */
    public function actionFile($filename)
    {
        Yii::$app->response->format = Response::FORMAT_RAW;

        $response = Yii::$app->getResponse();
        $response->headers->set('Content-Type', 'application/pdf');

        return Yii::$app->minio->read($filename);
    }

    /**
     * @return bool
     * @throws \yii\base\Exception
     */
    public function actionUploadFiles()
    {
        $model = new UploadForm();
        $listFiles = UploadedFile::getInstances($model, "files");

        if (!empty($listFiles)) {
            foreach ($listFiles as $file) {
                Yii::$app->minio
                    ->writeStream(
                        sprintf("%s.%s", Yii::$app->security->generateRandomString(), $file->extension),
                        fopen($file->tempName, 'r+')
                    );
            }

            return true;
        }

        return false;
    }

    /**
     * @param $filename
     * @return bool
     */

    public function actionDeleteFile($filename)
    {
        $exists = Yii::$app->minio->has($filename);

        if ($exists) {
            Yii::$app->minio->delete($filename);

            return true;
        }

        return false;
    }
}

frontend/views/main/index.php
<?php

use yii\helpers\Url;
use yii\widgets\ActiveForm;
use kartik\file\FileInput;

/**
 * @var $model \frontend\models\UploadForm
 * @var $listObjects array
 */

Yii::$app->name = 'Task e-queo.com'
?>

<div class="container">

    <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

    <div class="col-xs-12">
        <?php

        $options = [];
        $imgPath = [];

        $uploadFileUrl = Url::to(['/main/upload-files']);

        if ($listObjects) {
            $imgFullPath = Yii::getAlias("@frontend") . "/main/file?filename=";

            foreach ($listObjects as $object) {
                $fileName = $object['key'];
                $deleteUrl = Url::to(["/main/delete-file?filename=" . $fileName]);
                $imgPath[] = Url::to('http://' . $_SERVER['HTTP_HOST'] . '/main/file?filename=') . $fileName;

                $options[] =
                    [
                        'caption' => $fileName,
                        'url' => $deleteUrl,
                        'size' => $object['size'],
                        'key' => $fileName,
                    ];
            }
        }
        ?>

        <?=
        $form->field($model, 'files[]')
            ->widget(
                FileInput::class,
                [
                    'attribute' => 'files[]',
                    'name' => 'files[]',
                    'options' => [
                        'accept' => 'application/pdf',
                        'multiple' => true,
                    ],
                    'pluginOptions' => [
                        'previewFileType' => 'any',
                        "uploadAsync" => true,
                        'showPreview' => true,
                        'showUpload' => true,
                        'showCaption' => false,
                        'showDrag' => true,
                        'uploadUrl' => $uploadFileUrl,
                        'initialPreviewConfig' => $options,
                        'initialPreview' => $imgPath,
                        'initialPreviewAsData' => true,
                        'initialPreviewShowDelete' => true,
                        'overwriteInitial' => true,
                        'resizeImages' => true,
                        'layoutTemplates' => [!$listObjects ?: 'actionUpload' => '',]
                    ],
                ]);
        ?>
    </div>
    <?php ActiveForm::end(); ?>

</div>